In [98]:
import numpy as np


# sk - отклонение х по сравнению с предыдущей точкой
# yk - отклонение граиента по сравнению с предыдущей точкой
def update_hessian(old_hessian, sk, yk):
    ro = 1 / (np.dot(yk.T, sk))
    I = np.eye(old_hessian.shape[0])

    term1 = I - np.dot(ro * sk, yk.T)
    term2 = I - np.dot(ro * yk, sk.T)
    term3 = np.dot(ro * sk, sk.T)
    
    new_hessian = np.dot(np.dot(term1, old_hessian), term2) + term3
    
    
    return new_hessian

In [99]:
# Для проверки взял функцию x1^3+2*x2^3+3*x3^3
old_hessian = np.array([
    [12, 0, 0], 
    [0, 24, 0],
    [0, 0, 36]])
sk = np.array([1, 2, -1])
yk = np.array([15, 72, -27])

# Update the Hessian
new_hessian = update_hessian(old_hessian, sk, yk)

# Print the updated Hessian
print(new_hessian)

[[60.03225806 36.03225806 24.03225806]
 [36.03225806 48.03225806 12.03225806]
 [24.03225806 12.03225806 36.03225806]]


In [100]:
# Update the Hessian
new_hessian = update_hessian(new_hessian, sk, yk)

# Print the updated Hessian
print(new_hessian)

[[108.16129032 108.16129032 120.16129032]
 [108.16129032 144.16129032 132.16129032]
 [120.16129032 132.16129032 180.16129032]]


In [101]:
# Update the Hessian
new_hessian = update_hessian(new_hessian, sk, yk)

# Print the updated Hessian
print(new_hessian)

[[588.67741935 540.67741935 504.67741935]
 [540.67741935 528.67741935 468.67741935]
 [504.67741935 468.67741935 468.67741935]]


In [102]:
# На первом шаге вообще должен получаться такой Гессиан, если решать аналитически:
# [18, 0, 0]
# [0, 48, 0]
# [0, 0, 18]

# Функция x1^3+2*x2^3+3*x3^3
# x1 = [2, 2, 2]
# x2 = [3, 4, 1]

# grad(f(x)) = (3x1^2, 6x2^2, 9x3^2)